In [41]:
import time
import sys
import dis

In [2]:
start_time = time.time()
for x in range(1000000):
    x+=1
seconds = time.time() - start_time
print('1:', seconds)

1: 0.08741402626037598


In [4]:
data = [ 1, 2, -4, -3]
start_time = time.time()
for i in range(len(data)):
    if data[i] < 0:
        data[i] = 0
seconds = time.time() - start_time
print('1:', seconds, data)

1: 8.511543273925781e-05 [1, 2, 0, 0]


In [5]:
data = [ 1, 2, -4, -3]
start_time = time.time()
for idx, num in enumerate(data):
    if num < 0:
        data[idx] = 0
seconds = time.time() - start_time
print('1:', seconds, data)

1: 8.225440979003906e-05 [1, 2, 0, 0]


In [6]:
squares = []
for i in range(10):
    squares.append(i*i)
    
print (squares)
#better 
squares = [i*i for i in range(10)]
print (squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [12]:
data = [3, 5, 1, 10, 9]
sorted_data = sorted(data, reverse=False)
print (sorted_data)

data = [{"name": "Max", "age": 6},
       {"name": "Lisa", "age": 12},
       {"name": "Ben", "age": 18}]
sorted_data = sorted(data, key = lambda x: x["age"], reverse=True)
print (sorted_data)

[1, 3, 5, 9, 10]
[{'name': 'Ben', 'age': 18}, {'name': 'Lisa', 'age': 12}, {'name': 'Max', 'age': 6}]


In [13]:
my_list = [1,2,3,3,3,4,4,5,5,5,6,6,6,6,7]
my_set=set(my_list)
print (my_set)

{1, 2, 3, 4, 5, 6, 7}


In [17]:
my_list = [i for i in range(10000)]
print (sum(my_list))
print (sys.getsizeof(my_list), "bytes")

#better
my_gen = (i for i in range(10000))
print (sum(my_gen))
print (sys.getsizeof(my_gen), "bytes")

49995000
87632 bytes
49995000
128 bytes


In [20]:
my_dict = {"item": "footbal", "price": 10.00}
count = my_dict.get("count", 0)
print (count)

count = my_dict.setdefault("count", 0)
print (count)

print (my_dict)

0
0
{'item': 'footbal', 'price': 10.0, 'count': 0}


In [32]:
from collections import Counter

my_list = [10,10,9,6,6,6,6,5,5,5,5,4,4,4,3,3,3,33]
counter = Counter(my_list)

print (counter)
print (counter[6])

most_common = counter.most_common(1)
print (most_common)

print (most_common[0][1])

Counter({6: 4, 5: 4, 4: 3, 3: 3, 10: 2, 9: 1, 33: 1})
4
[(6, 4)]
4


In [39]:
name = "Serg"
my_string = f"Hello {name}!"
print (my_string)


i =10 
print (f"{i} squared is {i*i}")

Hello Serg!
10 squared is 100


In [40]:
d1 = {"name": "Serg", "age": 30}
d2 = {"name": "Serg", "city": "Moscow"}
merge_dict = {**d1, **d2}

print (merge_dict)

{'name': 'Serg', 'age': 30, 'city': 'Moscow'}


In [44]:
import numpy as np
vector_row = np.array([1, 2, 3])
vector_column = np.array([[1],
                          [2],
                          [3]])
matrix = np.array([[1, 2, 3],
                          [2, 1, 0],
                          [3, 2, 1]])
v_v = vector_row * vector_column
print (v_v)
v_m = vector_row * matrix
print (v_m)
v_c_m = vector_column * matrix
print (v_c_m)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 4 9]
 [2 2 0]
 [3 4 3]]
[[1 2 3]
 [4 2 0]
 [9 6 3]]
