In [3]:
import time
import sys
import dis

In [2]:
start_time = time.time()
for x in range(1000000):
    x+=1
seconds = time.time() - start_time
print('1:', seconds)

1: 0.08741402626037598


In [4]:
data = [ 1, 2, -4, -3]
start_time = time.time()
for i in range(len(data)):
    if data[i] < 0:
        data[i] = 0
seconds = time.time() - start_time
print('1:', seconds, data)

1: 8.511543273925781e-05 [1, 2, 0, 0]


In [5]:
data = [ 1, 2, -4, -3]
start_time = time.time()
for idx, num in enumerate(data):
    if num < 0:
        data[idx] = 0
seconds = time.time() - start_time
print('1:', seconds, data)

1: 8.225440979003906e-05 [1, 2, 0, 0]


In [6]:
squares = []
for i in range(10):
    squares.append(i*i)
    
print (squares)
#better 
squares = [i*i for i in range(10)]
print (squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [12]:
data = [3, 5, 1, 10, 9]
sorted_data = sorted(data, reverse=False)
print (sorted_data)

data = [{"name": "Max", "age": 6},
       {"name": "Lisa", "age": 12},
       {"name": "Ben", "age": 18}]
sorted_data = sorted(data, key = lambda x: x["age"], reverse=True)
print (sorted_data)

[1, 3, 5, 9, 10]
[{'name': 'Ben', 'age': 18}, {'name': 'Lisa', 'age': 12}, {'name': 'Max', 'age': 6}]


In [13]:
my_list = [1,2,3,3,3,4,4,5,5,5,6,6,6,6,7]
my_set=set(my_list)
print (my_set)

{1, 2, 3, 4, 5, 6, 7}


In [17]:
my_list = [i for i in range(10000)]
print (sum(my_list))
print (sys.getsizeof(my_list), "bytes")

#better
my_gen = (i for i in range(10000))
print (sum(my_gen))
print (sys.getsizeof(my_gen), "bytes")

49995000
87632 bytes
49995000
128 bytes


In [20]:
my_dict = {"item": "footbal", "price": 10.00}
count = my_dict.get("count", 0)
print (count)

count = my_dict.setdefault("count", 0)
print (count)

print (my_dict)

0
0
{'item': 'footbal', 'price': 10.0, 'count': 0}


In [32]:
from collections import Counter

my_list = [10,10,9,6,6,6,6,5,5,5,5,4,4,4,3,3,3,33]
counter = Counter(my_list)

print (counter)
print (counter[6])

most_common = counter.most_common(1)
print (most_common)

print (most_common[0][1])

Counter({6: 4, 5: 4, 4: 3, 3: 3, 10: 2, 9: 1, 33: 1})
4
[(6, 4)]
4


In [1]:
from typing import Optional

In [39]:
name = "Serg"
my_string = f"Hello {name}!"
print (my_string)


i =10 
print (f"{i} squared is {i*i}")

Hello Serg!
10 squared is 100


In [40]:
d1 = {"name": "Serg", "age": 30}
d2 = {"name": "Serg", "city": "Moscow"}
merge_dict = {**d1, **d2}

print (merge_dict)

{'name': 'Serg', 'age': 30, 'city': 'Moscow'}


In [44]:
import numpy as np
vector_row = np.array([1, 2, 3])
vector_column = np.array([[1],
                          [2],
                          [3]])
matrix = np.array([[1, 2, 3],
                          [2, 1, 0],
                          [3, 2, 1]])
v_v = vector_row * vector_column
print (v_v)
v_m = vector_row * matrix
print (v_m)
v_c_m = vector_column * matrix
print (v_c_m)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 4 9]
 [2 2 0]
 [3 4 3]]
[[1 2 3]
 [4 2 0]
 [9 6 3]]


In [6]:
int(time.time())

1595235476

In [3]:
#https://spacy.io/

In [52]:
#https://prodi.gy/docs
#http://pythontutor.com/live.html#mode=edit

<h2>Python к вершинам местерства</h2>

In [11]:
#именованные кортежи
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
#print (tokyo, '\n', tokyo.population, tokyo.coordinates)

In [19]:
#t

In [20]:
#perf_counter

In [21]:
#функции высшего порядка
fruits = ['strawberry', 'fig', 'apple', 'cherry', 'raspberry', 'banana']
sorted(fruits, key=len)

['fig', 'apple', 'cherry', 'banana', 'raspberry', 'strawberry']

In [30]:
#альтернативы функциям map filter reduce
def factorial(n):
    '''returns n!'''
    return 1 if n < 2 else n*factorial(n-1)
fact = factorial
print (list(map(fact, range(6))))
print ([fact(n) for n in range(6)])
print (list(map(factorial, filter(lambda n: n % 2, range(6)))))
print ([factorial(n) for n in range(6) if n % 2])

from functools import reduce
from operator import add
print (reduce(add, range(100)))
print (sum(range(100)))

[1, 1, 2, 6, 24, 120]
[1, 1, 2, 6, 24, 120]
[1, 6, 120]
[1, 6, 120]
4950
4950


In [35]:
#замыкания
def make_averager():
    series = []
    def averager(new_value):
        series.append(new_value)
        total = sum(series)
        return total/len(series)
    return averager

avg = make_averager()
print (avg(10))
print (avg(11))
print (avg(20))



10.0
10.5
13.666666666666666


In [36]:
#вычисление накопительного среднего без хранения всей истории
def make_averager():
    count = 0
    total = 0
    def averager(new_value):
        nonlocal count, total
        count += 1
        total += new_value
        return total/count
    return averager

avg = make_averager()
print (avg(10))
print (avg(11))
print (avg(20))

10.0
10.5
13.666666666666666


In [51]:
#простой декоратор, для вывода времени выполнения функции
import time

def clock(func):
    def clocked(*args):
        t0 = time.perf_counter()
        result = func(*args)
        elapsed = time.perf_counter() - t0
        name = func.__name__
        arg_str = ', '.join(repr(arg) for arg in args)
        print ('[%0.8fs] %s(%s) -> %r' % (elapsed, name, arg_str, result))
        return result
    return clocked

@clock
def snooze(seconds):
    time.sleep(seconds)
    
@clock
def factorial(n):
    return 1 if n < 2 else n*factorial(n-1)

if __name__=='__main__':
    print ('*' * 20, 'Calling snooze(.123)')
    snooze(.123)
    print ('*' * 20, 'Calling factorial(6)')
    print ('6! =', factorial(6))

******************** Calling snooze(.123)
[0.12651968s] snooze(0.123) -> None
******************** Calling factorial(6)
[0.00000061s] factorial(1) -> 1
[0.00002937s] factorial(2) -> 2
[0.00007076s] factorial(3) -> 6
[0.00010036s] factorial(4) -> 24
[0.00012178s] factorial(5) -> 120
[0.00014415s] factorial(6) -> 720
6! = 720


In [46]:
#параметризированный декоратор cloc
import time

DEFAULT_FMT = '[{elapsed:0.8f}s] {name}({args}) -> {result}'


def clock(fmt=DEFAULT_FMT):
    def decorate(func):
        def clocked(*_args):
            t0 = time.time()
            _result = func(*_args)
            elapsed = time.time() - t0
            name = func.__name__
            args = ', '.join(repr(arg) for arg in _args)
            result = repr(_result)
            print (fmt.format(**locals()))
            return _result
        return clocked
    return decorate


if __name__=='__main__':
    @clock()
    def snooze(seconds):
        time.sleep(seconds)
    
    for i in range(3):
        snooze(.123)
@clock('{name}({args}) dt={elapsed:0.3f}s')
def snooze(seconds):
    time.sleep(seconds)

for i in range(3):
    snooze(.123)


[0.12314510s] snooze(0.123) -> None
[0.12303209s] snooze(0.123) -> None
[0.12334633s] snooze(0.123) -> None
snooze(0.123) dt=0.127s
snooze(0.123) dt=0.127s
snooze(0.123) dt=0.127s


In [47]:
#генераторная функция печатующая сообщения во время выполнения
def gen_AB():
    print ('start')
    yield 'A'
    print ('continue')
    yield 'B'
    print ('end')
    
for c in gen_AB():
    print ('--->', c)

start
---> A
continue
---> B
end
