In [6]:
import time
import sys
import dis

In [7]:
start_time = time.time()
for x in range(1000000):
    x+=1
seconds = time.time() - start_time
print('1:', seconds)

1: 0.07523798942565918


In [70]:
data = [ 1, 2, -4, -3]
start_time = time.time()
for i in range(len(data)):
    if data[i] < 0:
        data[i] = 0
seconds = time.time() - start_time
print('1:', seconds, data)

1: 8.392333984375e-05 [1, 2, 0, 0]


In [71]:
data = [ 1, 2, -4, -3]
start_time = time.time()
for idx, num in enumerate(data):
    if num < 0:
        data[idx] = 0
seconds = time.time() - start_time
print('1:', seconds, data)

1: 8.225440979003906e-05 [1, 2, 0, 0]


In [72]:
squares = []
for i in range(10):
    squares.append(i*i)
    
print (squares)
#better 
squares = [i*i for i in range(10)]
print (squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [74]:
data = [3, 5, 1, 10, 9]
sorted_data = sorted(data, reverse=False)
print (sorted_data)

data = [{"name": "Max", "age": 6},
       {"name": "Lisa", "age": 12},
       {"name": "Ben", "age": 18}]
sorted_data = sorted(data, key = lambda x: x["age"], reverse=True)
print (sorted_data)

[1, 3, 5, 9, 10]
[{'name': 'Ben', 'age': 18}, {'name': 'Lisa', 'age': 12}, {'name': 'Max', 'age': 6}]


In [75]:
my_list = [1,2,3,3,3,4,4,5,5,5,6,6,6,6,7]
my_set=set(my_list)
print (my_set)

{1, 2, 3, 4, 5, 6, 7}


In [79]:
my_list = [i for i in range(10000)]
print (sum(my_list))
print (sys.getsizeof(my_list), "bytes")

#better
my_gen = (i for i in range(10000))
print (sum(my_gen))
print (sys.getsizeof(my_gen), "bytes")

49995000
87632 bytes
49995000
128 bytes


In [80]:
my_dict = {"item": "footbal", "price": 10.00}
count = my_dict.get("count", 0)
print (count)

count = my_dict.setdefault("count", 0)
print (count)

print (my_dict)

0
0
{'item': 'footbal', 'price': 10.0, 'count': 0}


In [81]:
from collections import Counter

my_list = [10,10,9,6,6,6,6,5,5,5,5,4,4,4,3,3,3,33]
counter = Counter(my_list)

print (counter)
print (counter[6])

most_common = counter.most_common(1)
print (most_common)

print (most_common[0][1])

Counter({6: 4, 5: 4, 4: 3, 3: 3, 10: 2, 9: 1, 33: 1})
4
[(6, 4)]
4


In [82]:
from typing import Optional

In [83]:
name = "Serg"
my_string = f"Hello {name}!"
print (my_string)


i =10 
print (f"{i} squared is {i*i}")

Hello Serg!
10 squared is 100


In [84]:
d1 = {"name": "Serg", "age": 30}
d2 = {"name": "Serg", "city": "Moscow"}
merge_dict = {**d1, **d2}

print (merge_dict)

{'name': 'Serg', 'age': 30, 'city': 'Moscow'}


In [85]:
import numpy as np
vector_row = np.array([1, 2, 3])
vector_column = np.array([[1],
                          [2],
                          [3]])
matrix = np.array([[1, 2, 3],
                          [2, 1, 0],
                          [3, 2, 1]])
v_v = vector_row * vector_column
print (v_v)
v_m = vector_row * matrix
print (v_m)
v_c_m = vector_column * matrix
print (v_c_m)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 4 9]
 [2 2 0]
 [3 4 3]]
[[1 2 3]
 [4 2 0]
 [9 6 3]]


In [86]:
int(time.time())

1600868371

In [3]:
#https://spacy.io/

In [87]:
#https://prodi.gy/docs
#http://pythontutor.com/live.html#mode=edit

<h2>Python к вершинам местерства</h2>

In [90]:
#именованные кортежи Data Class
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
print (tokyo, '\n', tokyo.population, tokyo.coordinates)

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667)) 
 36.933 (35.689722, 139.691667)


In [92]:
t

(1, 2, [30, 40, 50, 60])

In [20]:
#perf_counter

In [94]:
#функции высшего порядка
fruits = ['strawberry', 'fig', 'apple', 'cherry', 'raspberry', 'banana']
sorted(fruits, key=len)

['fig', 'apple', 'cherry', 'banana', 'raspberry', 'strawberry']

In [95]:
#альтернативы функциям map filter reduce
def factorial(n):
    '''returns n!'''
    return 1 if n < 2 else n*factorial(n-1)
fact = factorial
print (list(map(fact, range(6))))
print ([fact(n) for n in range(6)])
print (list(map(factorial, filter(lambda n: n % 2, range(6)))))
print ([factorial(n) for n in range(6) if n % 2])

from functools import reduce
from operator import add
print (reduce(add, range(100)))
print (sum(range(100)))

[1, 1, 2, 6, 24, 120]
[1, 1, 2, 6, 24, 120]
[1, 6, 120]
[1, 6, 120]
4950
4950


In [96]:
#замыкания
def make_averager():
    series = []
    def averager(new_value):
        series.append(new_value)
        total = sum(series)
        return total/len(series)
    return averager

avg = make_averager()
print (avg(10))
print (avg(11))
print (avg(20))



10.0
10.5
13.666666666666666


In [97]:
#вычисление накопительного среднего без хранения всей истории
def make_averager():
    count = 0
    total = 0
    def averager(new_value):
        nonlocal count, total
        count += 1
        total += new_value
        return total/count
    return averager

avg = make_averager()
print (avg(10))
print (avg(11))
print (avg(20))

10.0
10.5
13.666666666666666


In [98]:
#простой декоратор, для вывода времени выполнения функции
import time

def clock(func):
    def clocked(*args):
        t0 = time.perf_counter()
        result = func(*args)
        elapsed = time.perf_counter() - t0
        name = func.__name__
        arg_str = ', '.join(repr(arg) for arg in args)
        print ('[%0.8fs] %s(%s) -> %r' % (elapsed, name, arg_str, result))
        return result
    return clocked

@clock
def snooze(seconds):
    time.sleep(seconds)
    
@clock
def factorial(n):
    return 1 if n < 2 else n*factorial(n-1)

if __name__=='__main__':
    print ('*' * 20, 'Calling snooze(.123)')
    snooze(.123)
    print ('*' * 20, 'Calling factorial(6)')
    print ('6! =', factorial(6))

******************** Calling snooze(.123)
[0.12693593s] snooze(0.123) -> None
******************** Calling factorial(6)
[0.00000110s] factorial(1) -> 1
[0.00067163s] factorial(2) -> 2
[0.00070361s] factorial(3) -> 6
[0.00072267s] factorial(4) -> 24
[0.00073986s] factorial(5) -> 120
[0.00075920s] factorial(6) -> 720
6! = 720


In [106]:
#параметризированный декоратор cloc
import time

DEFAULT_FMT = '[{elapsed:0.8f}s] {name}({args}) -> {result}'


def clock(fmt=DEFAULT_FMT):
    def decorate(func):
        def clocked(*_args):
            t0 = time.time()
            _result = func(*_args)
            elapsed = time.time() - t0
            name = func.__name__
            args = ', '.join(repr(arg) for arg in _args)
            result = repr(_result)
            print (fmt.format(**locals()))
            return _result
        return clocked
    return decorate


if __name__=='__main__':
    @clock()
    def snooze(seconds):
        time.sleep(seconds)
    
    for i in range(3):
        snooze(.123)
@clock('{name}({args}) dt={elapsed:0.3f}s')
def snooze(seconds):
    time.sleep(seconds)

for i in range(3):
    snooze(.123)


[0.12750006s] snooze(0.123) -> None
[0.12571907s] snooze(0.123) -> None
[0.12734532s] snooze(0.123) -> None
snooze(0.123) dt=0.127s
snooze(0.123) dt=0.128s
snooze(0.123) dt=0.126s


In [101]:
#генераторная функция печатующая сообщения во время выполнения
def gen_AB():
    print ('start')
    yield 'A'
    print ('continue')
    yield 'B'
    print ('end')
    
for c in gen_AB():
    print ('--->', c)

start
---> A
continue
---> B
end


In [113]:
@clock('{name}({args}) dt={elapsed:0.3f}s')
def loop(n):
    for x in range(1000000):
        x+=n
    return x

for i in range(3):
    loop(4)

loop(4) dt=0.058s
loop(4) dt=0.049s
loop(4) dt=0.046s


In [107]:
#https://pypi.org/project/phonenumbers/

In [109]:
#import furl

In [117]:
textwrap.shorten("Hello  world!", width=12)

'Hello world!'

In [115]:
import textwrap

In [118]:
textwrap.shorten("Hello world", width=10, placeholder="...")

'Hello...'

In [167]:
texttest="""
sasdafhdjkasl as;djfk ;jsjdaf .

Shakjdfhks sdafjhsaf asdflha! dsfalhs lfa
sakf. 


aljdfj 


a

ff
"""


In [168]:
print(repr(textwrap.dedent(texttest)))

'\nsasdafhdjkasl as;djfk ;jsjdaf .\n\nShakjdfhks sdafjhsaf asdflha! dsfalhs lfa\nsakf. \n\n\naljdfj \n\n\na\n\nff\n'


In [160]:

print(repr(textwrap.wrap(texttest, fix_sentence_endings=False)))

[' sasdafhdjkasl as;djfk ;jsjdaf .  Shakjdfhks sdafjhsaf asdflha!', 'dsfalhs lfa sakf.    aljdfj    a']


In [161]:

print(repr(textwrap.wrap(texttest, fix_sentence_endings=True)))

[' sasdafhdjkasl as;djfk ;jsjdaf .  Shakjdfhks sdafjhsaf asdflha!', 'dsfalhs lfa sakf.    aljdfj    a']


In [132]:

print(repr(textwrap.wrap(texttest)))

[' sasdafhdjkas shakjdfhks sdafjhsaf asdflha! dsfalhs lfa sakf.', 'aljdfj    a']


In [139]:

print(repr(textwrap.fill(texttest)))

' sasdafhdjkas shakjdfhks sdafjhsaf asdflha! dsfalhs lfa sakf.\naljdfj    a'


In [134]:
import difflib

In [137]:
s1 = ['bacon\n', 'eggy\n', 'ham\n', 'guido\n']
s2 = ['python\n', 'eggy\n', 'hamster\n', 'guido\n']
sys.stdout.writelines(difflib.context_diff(s1, s2, fromfile='before.py', tofile='after.py'))

*** before.py
--- after.py
***************
*** 1,4 ****
! bacon
  eggy
! ham
  guido
--- 1,4 ----
! python
  eggy
! hamster
  guido


In [138]:
difflib.get_close_matches('appel', ['ape', 'apple', 'peach', 'puppy'])

['apple', 'ape']

In [169]:
import base64

In [174]:
print (base64.b64decode('hkahdfga='))

b'\x86F\xa1u\xf8\x1a'


In [185]:
encoded = base64.urlsafe_b64encode (bytes('data to be encoded==', "utf-8")) 

In [186]:
print (encoded)

b'ZGF0YSB0byBiZSBlbmNvZGVkPT0='


In [1]:

a = 'Какой то текст для теста '
print ('Reverse is : ', a[::-1])

Reverse is :   атсет ялд тскет от йокаК


In [3]:
#Check https
a = 'https://www.mos.ru/'
if a.startswith(('http://', 'https://')):
    print ('HTTP protocol ',  a)

HTTP protocol  https://www.mos.ru/


In [7]:
from collections import defaultdict
tree = lambda: defaultdict(tree)
root = tree()
root['menu']['id'] = 'file'
root['menu']['value'] = 'File'
root['menu']['menuitems']['new']['value'] = 'New'
root['menu']['menuitems']['new']['onclick'] = 'new();'

print (tree, root)

<function <lambda> at 0x7fd27d1fbc20> defaultdict(<function <lambda> at 0x7fd27d1fbc20>, {'menu': defaultdict(<function <lambda> at 0x7fd27d1fbc20>, {'id': 'file', 'value': 'File', 'menuitems': defaultdict(<function <lambda> at 0x7fd27d1fbc20>, {'new': defaultdict(<function <lambda> at 0x7fd27d1fbc20>, {'value': 'New', 'onclick': 'new();'})})})})


In [14]:
from xml.dom.minidom import parse, parseString
from urllib import request
print (parse(request.urlopen('https://www.mk.ru/rss/yandex/index.xml')).toprettyxml())

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [15]:
print (min([10, 1, -4, 5, -0.5]))
print (max([10, 1, -4, 5, -0.5]))

-4
10


In [16]:
text = '1 2 3 4'
result = list(map(lambda x: int(x), text.split()))
result

[1, 2, 3, 4]

In [18]:
#extended unpacking
a, *b, c = [1, 2, 3, 4, 5]
a, b, c

(1, [2, 3, 4], 5)

In [19]:
import random
print ("".join([random.choice('qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890@#!$%&*_-+=?') for i in range(23)]))

!O$=U8K$hnIFJpEno?rfgxr


In [22]:
!python3 -m http.server 8000


Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [16/Jun/2021 11:44:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Jun/2021 11:44:42] code 404, message File not found
127.0.0.1 - - [16/Jun/2021 11:44:42] "GET /favicon.ico HTTP/1.1" 404 -
^C

Keyboard interrupt received, exiting.


In [25]:
import numpy as np
n1 = np.random.randint(0, 3, 7)
n1 

array([1, 0, 0, 0, 0, 2, 2])

In [26]:
n1[::-1]

array([2, 2, 0, 0, 0, 0, 1])

In [27]:
np.flatnonzero(n1 == 2)

array([5, 6])

In [28]:
np.tile(n1, [3, 1])

array([[1, 0, 0, 0, 0, 2, 2],
       [1, 0, 0, 0, 0, 2, 2],
       [1, 0, 0, 0, 0, 2, 2]])

In [29]:
np.clip(n1, 0, 1)

array([1, 0, 0, 0, 0, 1, 1])

In [30]:
x1 = np.random.rand(10)
x2 = (x1**2 + 2*x1 +1)**.5 - 1 
print (np.all(x1 == x2))
print (np.allclose(x1 , x2, 1e-9))

False
True


In [31]:
np.percentile(np.random.rand(10), np.arange(0, 110, 10))

array([0.03742033, 0.14207119, 0.28316341, 0.36740134, 0.52871226,
       0.63685073, 0.72668189, 0.85245089, 0.89595573, 0.94084339,
       0.96724484])

In [32]:
bins = [0, 5, 10, 15]
x = np.random.randint(-5, 20, 10)
print (x)
print (np.searchsorted(bins, x))

[17 11 -5 17 16 13  8  3 -4 16]
[4 3 0 4 4 3 2 1 0 4]


In [34]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print ('a shape {} {}: b shape {} {}'.format(a.shape, a, b.shape, b))
a+b

a shape (3,) [0 1 2]: b shape (3, 1) [[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [53]:
import pandas as pd

In [54]:
df = pd.DataFrame(
              {"color" : ['R' ,'G', 'B'],
               "price" : [100, 120, 90],
               "time" : ['2018-05-06 12:12:12', '2018-05-06 13:10:00', '2018-05-07 14:14:00'],
               "type": [0, 1, 0]},
            index = [1, 2, 3])

In [37]:
df[:2]

color  price                 time  type
1     R    100  2018-05-06 12:12:12     0
2     G    120  2018-05-06 13:10:00     1

In [38]:
def map_function(row):
    return '{}_{}'.format(row['color'], row['type'])

df['ome_col'] = df.apply(map_function,  axis=1)

In [39]:
df.head()

color  price                 time  type ome_col
1     R    100  2018-05-06 12:12:12     0     R_0
2     G    120  2018-05-06 13:10:00     1     G_1
3     B     90  2018-05-07 14:14:00     0     B_0

In [40]:
df.groupby('type')['color'].value_counts()

type  color
0     B        1
      R        1
1     G        1
Name: color, dtype: int64

In [41]:
df.groupby('type')['color'].value_counts().unstack().fillna(0)

color    B    G    R
type                
0      1.0  0.0  1.0
1      0.0  1.0  0.0

In [42]:
pd.pivot_table(df, index=['type'], values=['price'], columns=['color'])

price              
color     B      G      R
type                     
0      90.0    NaN  100.0
1       NaN  120.0    NaN

In [61]:
df['time'] = pd.to_datetime(df['time'])
_df = df.set_index('time')
_df.resample('1h').count().color

time
2018-05-06 12:00:00    1
2018-05-06 13:00:00    1
2018-05-06 14:00:00    0
2018-05-06 15:00:00    0
2018-05-06 16:00:00    0
2018-05-06 17:00:00    0
2018-05-06 18:00:00    0
2018-05-06 19:00:00    0
2018-05-06 20:00:00    0
2018-05-06 21:00:00    0
2018-05-06 22:00:00    0
2018-05-06 23:00:00    0
2018-05-07 00:00:00    0
2018-05-07 01:00:00    0
2018-05-07 02:00:00    0
2018-05-07 03:00:00    0
2018-05-07 04:00:00    0
2018-05-07 05:00:00    0
2018-05-07 06:00:00    0
2018-05-07 07:00:00    0
2018-05-07 08:00:00    0
2018-05-07 09:00:00    0
2018-05-07 10:00:00    0
2018-05-07 11:00:00    0
2018-05-07 12:00:00    0
2018-05-07 13:00:00    0
2018-05-07 14:00:00    1
Freq: H, Name: color, dtype: int64

In [60]:

df['time'] = pd.to_datetime(df['time'])
df = df.sort_values(by='time')
df['time_diff'] = df['time2'].diff()
df['sec_diff'] = df.time_diff.dt.total_seconds()
df['row_duration'] = df.time_diff.shift(-1)
df[['time_diff', 'sec_diff', 'row_duration']][:3]

time_diff  sec_diff    row_duration
1             NaT       NaN 0 days 00:57:48
2 0 days 00:57:48    3468.0 1 days 01:04:00
3 1 days 01:04:00   90240.0             NaT

In [49]:
pd.to_datetime('2018-05-06 12:12:12'), pd.to_datetime('1623845282', unit='ms'), pd.to_datetime('1623845282', unit='s')

(Timestamp('2018-05-06 12:12:12'),
 Timestamp('1970-01-19 19:04:05.282000'),
 Timestamp('2021-06-16 12:08:02'))

In [62]:
df.price.pct_change()

1     NaN
2    0.20
3   -0.25
Name: price, dtype: float64

In [64]:
df.color.map({'R': 0, 'G': 1, 'B': 2}).astype(int)

1    0
2    1
3    2
Name: color, dtype: int64

In [68]:
import requests
response = requests.post('http://httpbin.org/post', data={'key1':'value1'})
#print(response.request.body)
print(response.request.headers)

{'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11', 'Content-Type': 'application/x-www-form-urlencoded'}


In [6]:
import stanza
stanza.download('ru')
stanza.download('ru')
#https://stanfordnlp.github.io/stanza/training.html

2021-07-20 15:40:56 INFO: Downloading default packages for language: ru (Russian)...


2021-07-20 15:40:58 INFO: File exists: /Users/sergeykarpovich/stanza_resources/ru/default.zip.
2021-07-20 15:41:02 INFO: Finished downloading models and saved to /Users/sergeykarpovich/stanza_resources.


In [15]:
def stanza_nlp_ru(text):
    nlp = stanza.Pipeline(lang='ru', processors='tokenize,ner')
    doc = nlp(text)
    print(*[f'entity: {ent.text}\ttype: {ent.type} ' for sent in doc.sentences for ent in sent.ents], sep='\n')


In [16]:
russian_text='''Участниками могут стать москвичи старше 18 лет, у которых есть полная учетная запись на портале mos.ru.
Общегородская проверка системы электронного голосования состоится с 29 по 30 июля. Она будет проходить в виде тестового голосования, с помощью которого можно будет проверить исправность системы и ее устойчивость к нагрузкам. Принять участие смогут москвичи старше 18 лет, у которых есть полная учетная запись на портале mos.ru.

Грядущее Путин Владимир тестовое голосование Собянин станет седьмым по счету. Оно позволит узнать мнение москвичей по важным для города темам и проверить корректность работы системы в условиях больших нагрузок и готовность к внешним атакам. Пользователям предстоит ответить на два вопроса.

Проконтролировать Магистратль исправность системы смогут не только разработчики и обычные москвичи, но и хакеры. Те из них, кто сумеет взломать систему или оказать существенное влияние на ее работу, получат денежное вознаграждение.

Безопасность системы и удобство ее использования проверяют в рамках подготовки к голосованию, которое пройдет в сентябре этого года. С 17 по 19 сентября по всей России состоятся выборы в Государственную Думу, а в некоторых районах — еще и в Московскую городскую Думу и советы муниципальных депутатов. Проголосовать москвичи смогут как на участках, так и онлайн.'''
stanza_nlp_ru(russian_text)

2021-07-20 15:59:41 INFO: Loading these models for language: ru (Russian):
| Processor | Package   |
-------------------------
| tokenize  | syntagrus |
| ner       | wikiner   |

2021-07-20 15:59:41 INFO: Use device: cpu
2021-07-20 15:59:41 INFO: Loading: tokenize
2021-07-20 15:59:41 INFO: Loading: ner
2021-07-20 15:59:42 INFO: Done loading processors!


entity: Общегородская	type: MISC 
entity: Путин Владимир	type: PER 
entity: Собянин	type: PER 
entity: москвичей	type: MISC 
entity: Магистратль	type: MISC 
entity: России	type: LOC 
entity: Государственную Думу	type: ORG 
entity: Московскую городскую Думу	type: LOC 


In [30]:
nlp = stanza.Pipeline(lang='ru', processors='tokenize,ner')
doc = nlp(russian_text)
print(*[f'entity: {ent.text}\ttype: {ent.type} \n {ent.tokens}' for sent in doc.sentences for ent in sent.ents], sep='\n')

2021-07-20 16:56:08 INFO: Loading these models for language: ru (Russian):
| Processor | Package   |
-------------------------
| tokenize  | syntagrus |
| ner       | wikiner   |

2021-07-20 16:56:08 INFO: Use device: cpu
2021-07-20 16:56:08 INFO: Loading: tokenize
2021-07-20 16:56:08 INFO: Loading: ner
2021-07-20 16:56:09 INFO: Done loading processors!


entity: Общегородская	type: MISC 
 [[
  {
    "id": 1,
    "text": "Общегородская",
    "start_char": 104,
    "end_char": 117,
    "ner": "S-MISC"
  }
]]
entity: Путин Владимир	type: PER 
 [[
  {
    "id": 2,
    "text": "Путин",
    "start_char": 442,
    "end_char": 447,
    "ner": "B-PER"
  }
], [
  {
    "id": 3,
    "text": "Владимир",
    "start_char": 448,
    "end_char": 456,
    "ner": "E-PER"
  }
]]
entity: Собянин	type: PER 
 [[
  {
    "id": 6,
    "text": "Собянин",
    "start_char": 478,
    "end_char": 485,
    "ner": "S-PER"
  }
]]
entity: москвичей	type: MISC 
 [[
  {
    "id": 5,
    "text": "москвичей",
    "start_char": 538,
    "end_char": 547,
    "ner": "S-MISC"
  }
]]
entity: Магистратль	type: MISC 
 [[
  {
    "id": 2,
    "text": "Магистратль",
    "start_char": 742,
    "end_char": 753,
    "ner": "S-MISC"
  }
]]
entity: России	type: LOC 
 [[
  {
    "id": 8,
    "text": "России",
    "start_char": 1118,
    "end_char": 1124,
    "ner": "S-LOC"
  }
]]
entity

In [33]:
nlp = stanza.Pipeline(lang='ru', processors='tokenize,ner')
doc = nlp("Проконтролировать Путину Собянин Магистратль исправность системы смогут не только разработчики и обычные москвичи,")
print(*[f'token: {token.text}\tner: {token.ner} \n {token.words}' for sent in doc.sentences for token in sent.tokens], sep='\n')

2021-07-20 16:58:29 INFO: Loading these models for language: ru (Russian):
| Processor | Package   |
-------------------------
| tokenize  | syntagrus |
| ner       | wikiner   |

2021-07-20 16:58:29 INFO: Use device: cpu
2021-07-20 16:58:29 INFO: Loading: tokenize
2021-07-20 16:58:29 INFO: Loading: ner
2021-07-20 16:58:30 INFO: Done loading processors!


token: Проконтролировать	ner: O 
 [{
  "id": 1,
  "text": "Проконтролировать",
  "start_char": 0,
  "end_char": 17
}]
token: Путину	ner: S-PER 
 [{
  "id": 2,
  "text": "Путину",
  "start_char": 18,
  "end_char": 24
}]
token: Собянин	ner: B-MISC 
 [{
  "id": 3,
  "text": "Собянин",
  "start_char": 25,
  "end_char": 32
}]
token: Магистратль	ner: E-MISC 
 [{
  "id": 4,
  "text": "Магистратль",
  "start_char": 33,
  "end_char": 44
}]
token: исправность	ner: O 
 [{
  "id": 5,
  "text": "исправность",
  "start_char": 45,
  "end_char": 56
}]
token: системы	ner: O 
 [{
  "id": 6,
  "text": "системы",
  "start_char": 57,
  "end_char": 64
}]
token: смогут	ner: O 
 [{
  "id": 7,
  "text": "смогут",
  "start_char": 65,
  "end_char": 71
}]
token: не	ner: O 
 [{
  "id": 8,
  "text": "не",
  "start_char": 72,
  "end_char": 74
}]
token: только	ner: O 
 [{
  "id": 9,
  "text": "только",
  "start_char": 75,
  "end_char": 81
}]
token: разработчики	ner: O 
 [{
  "id": 10,
  "text": "разработчики",
  "sta

In [20]:
nlp = stanza.Pipeline(lang='ru', processors='tokenize,pos')
doc = nlp('Проконтролировать Путин Собянин Магистратль исправность системы смогут не только разработчики и обычные москвичи,')
print(*[f'word: {word.text}\tupos: {word.upos}\txpos: {word.xpos}\tfeats: {word.feats if word.feats else "_"}' for sent in doc.sentences for word in sent.words], sep='\n')

2021-07-20 16:39:44 INFO: Loading these models for language: ru (Russian):
| Processor | Package   |
-------------------------
| tokenize  | syntagrus |
| pos       | syntagrus |

2021-07-20 16:39:44 INFO: Use device: cpu
2021-07-20 16:39:44 INFO: Loading: tokenize
2021-07-20 16:39:45 INFO: Loading: pos
2021-07-20 16:39:45 INFO: Done loading processors!


word: Проконтролировать	upos: VERB	xpos: None	feats: Aspect=Perf|VerbForm=Inf|Voice=Act
word: Путин	upos: PROPN	xpos: None	feats: Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing
word: Собянин	upos: PROPN	xpos: None	feats: Animacy=Anim|Case=Acc|Gender=Masc|Number=Sing
word: Магистратль	upos: PROPN	xpos: None	feats: Animacy=Anim|Case=Acc|Gender=Masc|Number=Sing
word: исправность	upos: NOUN	xpos: None	feats: Animacy=Inan|Case=Acc|Gender=Fem|Number=Sing
word: системы	upos: NOUN	xpos: None	feats: Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing
word: смогут	upos: VERB	xpos: None	feats: Aspect=Perf|Mood=Ind|Number=Plur|Person=3|Tense=Fut|VerbForm=Fin|Voice=Act
word: не	upos: PART	xpos: None	feats: _
word: только	upos: PART	xpos: None	feats: _
word: разработчики	upos: NOUN	xpos: None	feats: Animacy=Anim|Case=Nom|Gender=Masc|Number=Plur
word: и	upos: CCONJ	xpos: None	feats: _
word: обычные	upos: ADJ	xpos: None	feats: Case=Nom|Degree=Pos|Number=Plur
word: москвичи	upos: NOUN	xpos: None	feats: Animacy

In [36]:
from natasha import (
    Segmenter,
    MorphVocab,
    
    NewsEmbedding,
    NewsMorphTagger,
    NewsSyntaxParser,
    NewsNERTagger,
    
    PER,
    NamesExtractor,

    Doc
)

In [37]:
segmenter = Segmenter()
morph_vocab = MorphVocab()

emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)
syntax_parser = NewsSyntaxParser(emb)
ner_tagger = NewsNERTagger(emb)
names_extractor = NamesExtractor(morph_vocab)


In [38]:
text = 'Посол Израиля на Украине Йоэль Лион признался, что пришел в шок, узнав о решении властей Львовской области объявить 2019 год годом лидера запрещенной в России Организации украинских националистов (ОУН) Степана Бандеры. Свое заявление он разместил в Twitter. «Я не могу понять, как прославление тех, кто непосредственно принимал участие в ужасных антисемитских преступлениях, помогает бороться с антисемитизмом и ксенофобией. Украина не должна забывать о преступлениях, совершенных против украинских евреев, и никоим образом не отмечать их через почитание их исполнителей», — написал дипломат. 11 декабря Львовский областной совет принял решение провозгласить 2019 год в регионе годом Степана Бандеры в связи с празднованием 110-летия со дня рождения лидера ОУН (Бандера родился 1 января 1909 года). В июле аналогичное решение принял Житомирский областной совет. В начале месяца с предложением к президенту страны Петру Порошенко вернуть Бандере звание Героя Украины обратились депутаты Верховной Рады. Парламентарии уверены, что признание Бандеры национальным героем поможет в борьбе с подрывной деятельностью против Украины в информационном поле, а также остановит «распространение мифов, созданных российской пропагандой». Степан Бандера (1909-1959) был одним из лидеров Организации украинских националистов, выступающей за создание независимого государства на территориях с украиноязычным населением. В 2010 году в период президентства Виктора Ющенко Бандера был посмертно признан Героем Украины, однако впоследствии это решение было отменено судом. '

In [39]:
doc = Doc(text)

In [42]:
#doc.tag_ner(ner_tagger)
doc.ner.print()

Посол Израиля на Украине Йоэль Лион признался, что пришел в шок, узнав
      LOC────    LOC──── PER───────                                   
 о решении властей Львовской области объявить 2019 год годом лидера 
                   LOC──────────────                                
запрещенной в России Организации украинских националистов (ОУН) 
              LOC─── ORG─────────────────────────────────────── 
Степана Бандеры. Свое заявление он разместил в Twitter. «Я не могу 
PER────────────                                ORG────             
понять, как прославление тех, кто непосредственно принимал участие в 
ужасных антисемитских преступлениях, помогает бороться с 
антисемитизмом и ксенофобией. Украина не должна забывать о 
                              LOC────                      
преступлениях, совершенных против украинских евреев, и никоим образом 
не отмечать их через почитание их исполнителей», — написал дипломат. 
11 декабря Львовский областной совет принял решение провозгласить

In [4]:
image_url='/data/folder1/file_name.xlsx'

print (image_url.split("/")[-1])

file_name.xlsx


In [3]:
import pathlib

pathlib.Path("/tmp/images").mkdir(parents=True, exist_ok=True)

In [2]:
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
#import gensim; print("gensim", gensim.__version__)

macOS-10.16-x86_64-i386-64bit
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
NumPy 1.20.3
SciPy 1.7.1


In [3]:
#DataFrame https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
#https://www.kaggle.com/code/kashnitsky/topic-1-exploratory-data-analysis-with-pandas/notebook
#https://pandas.pydata.org/docs/pandas.pdf

In [2]:
#python -m pdb youscript.py


In [3]:
#NewProject #pipenv
#mkdir example
#cd example
#pipenv install ipykernel --dev
#pipenv run ipython kernel install --user --name=example


In [4]:
import sys 
sys.version_info

sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

In [15]:
import socket
hostname = socket.gethostname()

addresses = socket.getaddrinfo(hostname, None)

for address in addresses:
    #print (address[0].name)
    #print (address[4][0])
    print (address, address[0].name, address[4][0])

(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('10.60.20.1', 0)) AF_INET 10.60.20.1
(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.60.20.1', 0)) AF_INET 10.60.20.1


In [17]:
import psutil
print (psutil.cpu_stats(), psutil.cpu_percent())

scpustats(ctx_switches=6852, interrupts=141733, soft_interrupts=232774657, syscalls=219417) 21.1


In [37]:
#server status
import sys
import socket
import psutil
import click

HELP_TEXT='''
python: {program_name:s}

--help
'''

def python_version():
    return sys.version_info

def ip_address():
    hostname = socket.gethostname()

    addresses = socket.getaddrinfo(hostname, None)
    address_info=[]
    for address in addresses:
        address_info.append((address[0].name, address[4][0]))
    return address_info

def cpu_load():
    return psutil.cpu_percent()

def ram_available():
    return psutil.virtual_memory().available

def ac_connected():
    return psutil.sensors_battery().power_plugged
    

def show_sensors():
    print ("Version Python: {0.major}.{0.minor}".format(python_version()))
    for address in ip_address():
        print ("ip-address: {0[1]} ({0[0]})".format(address))
    print ("CPU: {:.1f}".format(cpu_load()))
    print ("Memory: {} MiB".format(ram_available() / 1024**2))
    print ("Sensor: {}".format(ac_connected()))
    
@click.command(help="Show sensor")
def command_line(argv):
    program_name, *arguments = argv
    if not arguments:
        show_sensors()
    elif arguments and arguments[0] == "--help":
        print (HELP_TEXT.format(program_name=program_name))
    return




if __name__ == '__main__':
    show_sensors()
    

Version Python: 3.9
ip-address: 10.60.20.1 (AF_INET)
ip-address: 10.60.20.1 (AF_INET)
CPU: 17.4
Memory: 847.83984375 MiB
Sensor: True


In [39]:
print (show_sensors())

Version Python: 3.9
ip-address: 10.60.20.1 (AF_INET)
ip-address: 10.60.20.1 (AF_INET)
CPU: 27.6
Memory: 802.2890625 MiB
Sensor: True
None


In [42]:
from fractions import Fraction
y = 1/4 * 2/3
print (y)
x = Fraction('1/4') * Fraction ('2/3')
print (x)

0.16666666666666666
1/6


In [48]:
import pytest
from collections import namedtuple

@pytest.fixture
def version():
    return namedtuple('sys_version', ('major', 'minor', 'micro', 'releaselevel', 'serial'))
    


In [51]:
print (cpu_load())

23.0


In [8]:
#Проверка аргумента

def has_negative_arguments(*args):
    for arg in args:
        if arg < 0:
            return True
        return False
    
def power(x , y):
    if has_negative_arguments(x, y):
        return 0 
    return x ** y

power (4 , 2)

16

In [11]:

def disallow_negative(func):
    def inner(*args):
        for arg in args:
            if arg < 0:
                return 0
            return func(*args)
    return inner

@disallow_negative
def power2(x, y):
    return x ** y


power2 (4, 2)

16

In [12]:
def example(x, y):
    a = x + y
    b = x * y
    c = b * a
    print (f"a: {a}, b: {b}, c: {c}")
    def get_value_of_c():
        print (f"Return c: {c}")
        return c
    return get_value_of_c


getter = example (1, 2)
print (getter())

a: 3, b: 2, c: 6
Return c: 6
6


In [13]:
def private_variable():
    value = None
    def set(new_value):
        nonlocal value
        value = new_value
    def get():
        return value
    return set, get

a_set, a_get = private_variable()
b_set, b_get = private_variable()

print (a_get,  a_set)

print (b_get, b_set)

a_set(10)
print (f"a={a_get()} b={b_get()}")

b_set(4)
print (f"a={a_get()} b={b_get()}")

<function private_variable.<locals>.get at 0x7fc8a8b86160> <function private_variable.<locals>.set at 0x7fc8a8b86040>
<function private_variable.<locals>.get at 0x7fc8a8b869d0> <function private_variable.<locals>.set at 0x7fc8a8b86700>
a=10 b=None
a=10 b=4


In [15]:
def outer(func):
    print (f"Decorator {func}")
    def inner(*args, **kwargs):
        print (f"Return {func}(*{args}, **{kwargs})")
        value = func (*args, **kwargs)
        print (f"Return {value}")
        return value
    return inner


@outer
def add_five(num):
    return num+5


print (add_five)
add_five(1)

Decorator <function add_five at 0x7fc8a8c99e50>
<function outer.<locals>.inner at 0x7fc8a8c99ca0>
Return <function add_five at 0x7fc8a8c99e50>(*(1,), **{})
Return 6


6

In [21]:
def add_integer_to_all_arguments(offset):
    def decorator(func):
        def inner(*args):
            args = [arg + offset for arg in args]
            return func(*args)
        return inner
    return decorator

@add_integer_to_all_arguments(10)
def power(x , y):
    return x ** y

@add_integer_to_all_arguments(3)
def add(x, y):
    return x + y

print (power)
print (power(0, 0))
print (add)
print (add (0 ,0))

<function add_integer_to_all_arguments.<locals>.decorator.<locals>.inner at 0x7fc8a89c2820>
10000000000
<function add_integer_to_all_arguments.<locals>.decorator.<locals>.inner at 0x7fc8a89c2670>
6


In [24]:
def add_to_session(session):
    for item in generator:
        session.add(item)
        yield item

In [25]:
import threading

def helloword():
    print ("Hello word")
    
thread = threading.Thread(
    target = helloword,
    name = "helloworld"
)
thread.start()
thread.join()

Hello word


In [26]:
import threading
class HelloWordThread(threading.Thread):
    def run(self):
        print ("Hello Word")
        
thread = HelloWordThread(name = "helloword")
thread.start()
thread.join()

Hello Word


In [27]:
import threading

numlock = threading.Lock()
num = 0

def increment():
    global num
    with numlock:
        num += 1
    return None 

In [30]:
async def offset():
    await asyncio.sleep(0)
    return 1 

In [32]:
offset()

<coroutine object offset at 0x7fc8a8e322c0>

In [41]:
import ipywidgets as widgets

def add_numbers(x, y):
    return print (x + y)

interact = widgets.interactive(add_numbers, x=100, y=100)
display(interact)

interactive(children=(IntSlider(value=100, description='x', max=300, min=-100), IntSlider(value=100, descripti…

In [42]:
import cProfile

In [44]:
%%prun -s cumulative 

import ipywidgets as widgets

def add_numbers(x, y):
    return print (x + y)

interact = widgets.interactive(add_numbers, x=100, y=100)
display(interact)

interactive(children=(IntSlider(value=100, description='x', max=300, min=-100), IntSlider(value=100, descripti…

         61738 function calls (52865 primitive calls) in 0.041 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.041    0.041 {built-in method builtins.exec}
        1    0.000    0.000    0.041    0.041 <string>:1(<module>)
        1    0.000    0.000    0.030    0.030 interaction.py:177(__init__)
     10/4    0.000    0.000    0.027    0.007 widget.py:409(__init__)
     10/4    0.000    0.000    0.026    0.006 widget.py:425(open)
4035/1635    0.001    0.000    0.023    0.000 traitlets.py:566(__get__)
     15/9    0.000    0.000    0.023    0.003 widget.py:492(get_state)
 1253/775    0.001    0.000    0.023    0.000 traitlets.py:535(get)
10105/5113    0.003    0.000    0.021    0.000 {built-in method builtins.getattr}
  356/104    0.001    0.000    0.020    0.000 traitlets.py:1567(trait_defaults)
   316/88    0.000    0.000    0.018    0.000 traitlets.py:502(default)
        6    0.000    0

In [45]:
import timeit

In [47]:
#import yappi

In [49]:
import tracemalloc

In [50]:
def get_item(variable, key, default=None):
    try:
        return variable[key]
    except TypeError:
        return default
    except KeyError:
        return default
    except IndexError:
        return default

In [51]:
#sys.exit(0) - срочный выход

In [32]:
import requests
TOKEN = "1152626634:AAGdRLHR2geMGSIab3Fz29bIFnpzoczAAQ4"
CHAT_ID = "213040478"
text = "Проверка связи"
url = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&text={text}"
#url = f"https://api.telegram.org/bot{TOKEN}/getUpdates"
r = requests.get(url)
print(r.json())

{'ok': True, 'result': {'message_id': 449, 'from': {'id': 1152626634, 'is_bot': True, 'first_name': 'HelpMos', 'username': 'HelpMos_bot'}, 'chat': {'id': 213040478, 'first_name': 'Сергей', 'last_name': 'Карпович', 'username': 'KarpovichSerg', 'type': 'private'}, 'date': 1657014071, 'text': 'Проверка связи'}}
